#!/usr/bin/perl
###########################################
use warnings;
use strict;

use Net::Amazon;

my $ua = Net::Amazon->new(
    token       => 'YOUR_AMZN_TOKEN',
);

my $resp = $ua->search(
    asin  => $ARGV[0],
);

if($resp->is_success()) {
    print $resp->as_string(), "\n";
} else {
    print "Error: ", 
          $resp->message(), "\n";
}
