#!/usr/bin/perl
###########################################
use warnings;
use strict;

use Net::Amazon;

my $ua = Net::Amazon->new(
    token       => $ENV{AMAZON_TOKEN},
);

my $resp = $ua->search(
    asin  => [qw(0596005083 0596005008 0672326043)],
    #asin  => "0596005083",
);

if($resp->is_success()) {
    for($resp->properties()) {
        print $_->as_string(), "\n";
    } 
} else {
    print "Error: ", 
          $resp->message(), "\n";
}
