#!/usr/bin/perl
###########################################
use warnings;
use strict;

use Net::Amazon;

my $ua = Net::Amazon->new(
    token       => $ENV{AMAZON_TOKEN},
    locale      => 'de',
);

my $resp = $ua->search(
    asin  => "3827313783",
);

if($resp->is_success()) {
    print $resp->as_string(), "\n";
} else {
    print "Error: ", 
          $resp->message(), "\n";
}
