#!/usr/bin/perl
###########################################
use warnings;
use strict;

use Net::Amazon;

#use Log::Log4perl qw(:easy);
#Log::Log4perl->easy_init($DEBUG);

my $ua = Net::Amazon->new(
   token       => $ENV{AMAZON_TOKEN},
   secret_key  => $ENV{AMAZON_SECRET_KEY},
   locale      => 'uk',
);

die "usage: $0 ean\n" unless defined $ARGV[0];

my $resp = $ua->search(
   ean  => $ARGV[0],
   mode => 'DVD',
);

if($resp->is_success()) {
   print $resp->as_string(), "\n";
} else {
   print "Error: ",
         $resp->message(), "\n";
}
