#!/usr/bin/perl
###########################################
use warnings;
use strict;

use Net::Amazon;

#use Log::Log4perl qw(:easy);
#Log::Log4perl->easy_init($DEBUG);

my $ua = Net::Amazon->new(
    associate_tag => $ENV{AMAZON_ASSOCIATE_TAG},
    token         => $ENV{AMAZON_TOKEN},
    secret_key    => $ENV{AMAZON_SECRET_KEY},
);

die "usage: $0 isbn\n" unless defined $ARGV[0];

my $resp = $ua->search(
   isbn => $ARGV[0],
);

if($resp->is_success()) {
   print $resp->as_string(), "\n";
} else {
   print "Error: ",
         $resp->message(), "\n";
}
