#!/usr/bin/perl
###########################################
# reviews
# Mike Schilli, 2003 (m@perlmeister.com)
###########################################
use warnings;
use strict;

use Net::Amazon;
use Net::Amazon::Request::Review;

use Log::Log4perl qw(:easy);
Log::Log4perl->easy_init({level => $DEBUG, layout => '%F{1}-%L: %m%n'});

my $ua = Net::Amazon->new(
    token       => 'YOUR_AMZN_TOKEN',
);

die "usage: $0 asin\n(use 0201360683 as " .
    "an example)\n" unless defined $ARGV[0];

my $req = Net::Amazon::Request::Review->new(
    asin  => $ARGV[0],
);

  # Response is Net::Amazon::ASIN::Response
my $resp = $ua->request($req);

if($resp->is_success()) {
    print $resp->as_string(), "\n";
} else {
    print "Error: ", 
          $resp->message(), "\n";
}
