#!/usr/bin/perl
###########################################
use warnings;
use strict;

use Net::Amazon;
#use Log::Log4perl qw(:easy);
#Log::Log4perl->easy_init($DEBUG);

my $ua = Net::Amazon->new(
    token       => $ENV{AMAZON_TOKEN},
    secret_key  => $ENV{AMAZON_SECRET_KEY},
);

die "usage: $0 upc [mode]\n(use " .
    "'093624843627 music' as an example)\n"
    unless defined $ARGV[0];


my %options;
$options{upc}  = $ARGV[0];
$options{mode} = $ARGV[1] if defined $ARGV[1];

my $resp = $ua->search(%options);

if($resp->is_success()) {
    print $resp->as_string(), "\n";
} else {
    print "Error: ", 
          $resp->message(), "\n";
}
