#!/usr/bin/perl
############################################################
# wishlist wishlist_id
# Mike Schilli <mschilli1@aol.com>, 2003
############################################################

use strict;
use warnings;

use Net::Amazon;
use Net::Amazon::Request::Wishlist;

#use Log::Log4perl qw(:easy);
#Log::Log4perl->easy_init($DEBUG);

die "usage: $0 wishlist_id\n" .
    "(use 1XL5DWOUFMFVJ as an example)\n" unless $ARGV[0];

my $ua = Net::Amazon->new(
    token       => $ENV{AMAZON_TOKEN},
);

my $req = Net::Amazon::Request::Wishlist->new(
    id  => $ARGV[0]
);

   # Response is of type Net::Amazon::ASIN::Response
my $resp = $ua->request($req);

print $resp->as_string, "\n";
